image: docker
services:
- docker:18-dind

website:
  except:
  - staging
  - production
  script:
  - |
    set -exo pipefail
    cd website
    docker build --pull .

api:
  except:
  - staging
  - production
  script:
  - |
    set -exo pipefail
    cd api
    docker build --pull .

website-deploy:
  only:
  - production
  script:
  - |
    set -exo pipefail
    cd website
    CONTAINER="${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/website"
    docker build --pull -t "$CONTAINER" .
    docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CONTAINER"
    docker push "$CONTAINER"

api-deploy:
  only:
  - staging
  - production
  script:
  - |
    set -exo pipefail
    cd api
    CONTAINER="${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/api"
    docker build --pull -t "$CONTAINER" .
    docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CONTAINER"
    docker push "$CONTAINER"
